pipeline {
    agent any

    tools{
      maven 'Maven 3.6.1'  
    }

    stages {
        stage('build') {
            steps {
                echo 'Compiling worker app'
                dir('worker'){
                  sh ' /var/lib/docker/volumes/setup_jenkins-data/_data/tools/hudson.tasks.Maven_MavenInstallation/Maven_3.6.1/bin/mvn compile'
                }
            }
        }
        stage('test') {
            steps {
                echo 'Running unit tests on worker app'
                sleep 6
            }
        }
        stage('package') {
            steps {
                echo 'Packaging worker app'
                sleep 10
            }
        }
    }
    
    post {
        always{
            echo "Build pipeline for worker is complete"
        }
    }
}

